from utils.util import dbToString
from optimization.prompts.Prompts import Prompts

class FrozenLakePrompts(Prompts):       
    def getReflectorPrompt(self, trajectory: str) -> str:        
        return [
            {
                "role": "system",
                "content": f'''
You are a reflection agent for navigation tasks in (non-)deterministic environments, that analyzes a strategy playbook based on navigation trajectory performance.
The strategy playbook was used to guide a value estimator LLM during a lookahead search in the navigation task.
Your job is to diagnose failures and evaluate how well the strategy playbook guided the value estimator used in lookahead search, based on a recent trajectory generated by navigating the environment.

# Inputs
## Current Strategy Playbook - A set of strategies, heuristics and common mistakes to avoid:                
{dbToString(self.policyDb) if self.policyDb is not None and dbToString(self.policyDb) else 'No strategies available yet!'}

## Trajectory of the a navigation agent that traversed the environment:
{trajectory if trajectory is not None else ''}

## About the navigation agent algorithm:
1. Performs a lookahead simulation from a given state with a certain depth and sample_size
2. The lookahead uses an LLM-based value estimator with: current state + possible moves + this policy
3. Executes the highest-rated move from the lookahead in the actual environment
4. Repeats

# Your Reflection Task:
1. **Trace Decisions**: At each turn, which move did the value estimator rate highest? Why?
2. **Evaluate Policy Impact**: 
   - Which policies influenced the value estimator's ratings?
   - Did they cause good moves to be rated higher or lower?
   - Did they cause bad moves to be rated higher or lower?
3. **Identify Failures**: Where did the value estimator give high ratings to moves that led to negative rewards?
4. **Diagnose Root Causes**:
   - Missing guidance: value estimator had no policy to distinguish good/bad moves
   - Misleading guidance: policy told value estimator to favor the wrong moves
   - Conflicting guidance: policies contradicted each other
5. **Tag Each Policy Bulletpoint**: 'helpful', 'harmful', or skip (neutral) based on:
   - Did it help the value estimator rate good moves higher?
   - Did it cause the value estimator to rate bad moves higher?
   - Was it irrelevant to this trajectory?
                    
## Scope of Policy Control:
The policy can ONLY influence how the value estimator rates moves.
The policy CANNOT:
- Change what moves are generated
- Filter or discard moves before rating
- Modify lookahead depth or sample size
- Add pre-processing or safety checks to the agent                  
The policy CAN:
- Guide the value estimator to rate certain moves higher/lower
- Provide heuristics for scoring moves based on state features
- Describe patterns that indicate good vs bad moves
                    
When analyzing failures, focus on: "Did the value estimator rate the wrong move too highly?"
NOT: "Did the agent fail to filter out bad moves?"
                                                         
## Critical Constraints
✓ Focus on how policies influenced value estimator's ratings
✓ Ground analysis in actual rewards received
✓ Suggest policy changes that guide value estimator better
✗ Don't learn specific positions (environment is dynamic/non-deterministic)
✗ Don't suggest changes to agent logic, lookahead depth, or move generation
✗ Don't suggest "filtering" or "discarding" moves - only rating them differently
                          
# Required Output (JSON only)
{{
  "reasoning": "[For each turn: What state? Which move was chosen (highest rated)? What reward? Which policies likely influenced that rating? Should that move have been rated lower/higher?]",
  "error_identification": "[Specific moves that were rated incorrectly by the value estimator. Example: 'Move DOWN was rated highest but led to -1 reward']",
  "root_cause_analysis": "[Why did the policy fail to guide ratings correctly? Was guidance missing, misleading, or conflicting? What should the value estimator have considered when rating moves?]",
  "correct_approach": "[How should the policy guide the value estimator differently? Example: 'Policy should tell value estimator to rate moves toward walls very low' NOT 'Agent should filter wall moves']",
  "key_insight": "[Generalizable principle for value estimation: What patterns/features should the value estimator consider when rating moves? Frame as rating guidance, not algorithmic changes.]",
  "bullet_tags": [{{"id": "example_id", "tag": "helpful|harmful"}}]
}}
                    
## Examples of Good vs Bad Suggestions
WRONG: "Discard paths in lookahead that lead to negative rewards"
RIGHT: "When rating moves, heavily penalize paths that lead to negative rewards in the lookahead"

WRONG: "Add a safety check to prevent moving into walls"
RIGHT: "Guide the value estimator to assign very low scores to moves that would hit walls"
'''
            }
        ]
    
    def getCuratorPrompt(self, trajectory, reflection) -> str:
        return [
            {
                "role": "system",
                "content": f'''
                    You are a policy curator for 2D navigation.
                    Your job: maintain a concise policy that helps a value estimator LLM rate moves during lookahead simulations.

                    
                    ## How The Navigation Agent Works
                    The agent is NOT an LLM. It's a simple algorithm that:
                    1. Performs lookahead simulation from a given state with a certain depth and sample_size
                    2. The lookahead uses an LLM-based value estimator with: current state + possible moves + this policy
                    3. Executes the highest-rated move from the lookahead in the actual environment
                    4. Repeats

                    The policy you maintain guides the value estimator's ratings. 
                    You CANNOT change the agent's search depth, move generation or execution logic.

                    
                    ## Core Principles
                    - **Focus on strategies, common mistakes, etc.**: Each bulletpoint should describe a strategy, tip, common mistake to avoid. Dont include environment specifics.
                    - **Quality over quantity**: 5-10 focused bulletpoints beats 20+ redundant ones
                    - **Merge over add**: Consolidate similar insights
                    - **Remove harmful**: Delete bulletpoints frequently tagged 'harmful' in reflections
                    - **One bulletpoint per tool call**: Each ADD/MODIFY/DELETE handles ONE entry

                    
                    ## CRITICAL: Tool Usage Requirements
                    You MUST use the provided tools via function calling. DO NOT write tool calls in your response text.
                    - NEVER write tool syntax like "ADD(...)" or "MODIFY(...)" in your response text
                    - The system will execute your tool calls automatically

                    ## CRITICAL: Your Scope of Control
                    You can ONLY influence the value estimator's ratings through policy guidance.
                    You CANNOT:
                    - Change what moves are generated
                    - Filter or discard moves before the value estimator sees them
                    - Modify the lookahead simulation logic
                    - Add pre-processing or safety checks

                    You CAN:
                    - Guide the value estimator to rate certain moves higher/lower
                    - Provide heuristics for scoring moves based on state features
                    - Describe patterns that indicate good vs bad moves

                    Examples:
                    WRONG: "Pre-filter unsafe moves before evaluation"  
                    RIGHT: "The value estimator should assign near-zero scores to moves onto hazardous tiles"

                    WRONG: "During lookahead, skip paths that..."
                    RIGHT: "When rating moves, penalize paths that..."
                    

                    ## Inputs
                    REFLECTION_BEGIN
                    {reflection if reflection is not None else ''}
                    REFLECTION_END

                    POLICY_BEGIN
                    {dbToString(self.policyDb) if self.policyDb is not None else 'No playbook available'}
                    POLICY_END

                    NAVIGATION_TRAJECTORY_BEGIN
                    {trajectory if trajectory is not None else ''}
                    NAVIGATION_TRAJECTORY_END

                    
                    ## Your Task
                    1. Review reflection tags: 'harmful' (remove these), 'helpful' (keep/merge), new insights
                    2. For each new insight from reflection's key_insight or correct_approach:
                       - Does similar advice exist? → MODIFY to merge
                       - Genuinely novel? → ADD (one bulletpoint per call)
                    3. If policy is comprehensive, do nothing
                    4. Remove entries frequently tagged 'harmful'
                    
                    ## CRITICAL: Tool Usage
                    Use the provided tools to apply these changes. Make sure to use the right parameters and valid JSON format.

                    The environment is dynamic and non-deterministic. Focus on guidance that helps the value estimator distinguish good moves from bad ones.
                    '''
            }
        ]
    
    def getCuratorTools(self) -> str:
        return [
    {
        "type": "function",
        "function": {
            "name": "ADD",
            "description": "Add a new policy entry that guides the value estimator to rate moves better. Use when insight is genuinely novel and cannot be merged with existing entries.",
            "parameters": {
                "type": "object",
                "properties": {
                    "section": {
                        "type": "string",
                        "description": "Section name (e.g., 'General Navigation Heuristics'). Reuse existing sections when possible."
                    },
                    "content": {
                        "type": "string",
                        "description": "Single bulletpoint guiding the value estimator on how to rate moves. Must focus on rating guidance, not agent behavior. Example: 'Rate moves toward goals higher than moves away from goals' NOT 'Agent should move toward goals'."
                    }
                },
                "required": ["section", "content"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "REMOVE",
            "description": "Remove a policy entry that was tagged 'harmful' or is redundant.",
            "parameters": {
                "type": "object",
                "properties": {
                    "bullet_id": {
                        "type": "string",
                        "description": "ID of the bulletpoint to remove."
                    }
                },
                "required": ["bullet_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "MODIFY",
            "description": "Merge or improve an existing policy entry. Prefer this over ADD when similar guidance already exists.",
            "parameters": {
                "type": "object",
                "properties": {
                    "bullet_id": {
                        "type": "string",
                        "description": "ID of the bulletpoint to modify."
                    },
                    "content": {
                        "type": "string",
                        "description": "New content that completely replaces the existing entry. Should focus on how the value estimator should rate moves."
                    }
                },
                "required": ["bullet_id", "content"]
            }
        }
    }
]